// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrXdE23z2CPO0WTpTyuAMpKXnf68rXSw',
    appId: '1:377794084770:web:5cb6bf83ec0fce0bfcbcfb',
    messagingSenderId: '377794084770',
    projectId: 'water-tank-automation-c1811',
    authDomain: 'water-tank-automation-c1811.firebaseapp.com',
    databaseURL: 'https://water-tank-automation-c1811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-tank-automation-c1811.appspot.com',
    measurementId: 'G-D2L7X8R2FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeA1Z93Wh-67V3FAo-y-bwoIcQL0dC-u4',
    appId: '1:377794084770:android:e1487954acefb9fffcbcfb',
    messagingSenderId: '377794084770',
    projectId: 'water-tank-automation-c1811',
    databaseURL: 'https://water-tank-automation-c1811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-tank-automation-c1811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4UbKfJN4Huex_wM_mJ8bDSwtjtqnXbSo',
    appId: '1:377794084770:ios:ad2e3f282c25b950fcbcfb',
    messagingSenderId: '377794084770',
    projectId: 'water-tank-automation-c1811',
    databaseURL: 'https://water-tank-automation-c1811-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-tank-automation-c1811.appspot.com',
    iosBundleId: 'com.example.waterTankAutomation',
  );
}